gword = [{text: 'sakai', size: 100},
{text: 'error', size: 50},
{text: 'sakaiportallogin', size: 50},
{text: 'presense', size: 50},
{text: 'rantscomments', size: 40},
{text: 'lmsvle', size: 40},
{text: 'memory', size: 40},
{text: 'with', size: 40},
{text: 'examples', size: 40},
{text: 'provider', size: 40},
{text: 'developers', size: 30},
{text: 'zero', size: 20},
{text: 'documentation', size: 20},
{text: 'lone', size: 20},
{text: 'conference', size: 20},
{text: 'authentication', size: 20},
{text: 'ldap', size: 20},
{text: 'song', size: 20},
{text: 'into', size: 20},
{text: 'break', size: 20},
{text: 'from', size: 20},
{text: 'report', size: 20},
{text: 'austin', size: 20},
{text: 'block', size: 20},
{text: 'logo', size: 20},
{text: 'call', size: 20},
{text: 'participation', size: 20}
];
